### ISSUE TITLE
Iframe Aspect Ratio/Height Problem

### ISSUE THREAD

**Issue by bthemez** [corbindavenport/superembed.js#2]
Hello

First of all, thank you for the script, It's great. I have been looking for something like this. However, I having some problem with its aspect ratio/Iframe height problem.

I have used the script here [http://sublime-bthemez.blogspot.in/](http://sublime-bthemez.blogspot.in/) and in the very first post, you'll see It is not keeping its aspect ratio and increased the iframe height.

**Comment by corbindavenport** [comment]
Yeah I can see it's pretty broken... I'm not sure how to fix it. I'll take a look at it in depth and see what I can find.

**Comment by corbindavenport** [comment]
It turned out removing the optional calc() functionality fixed it :)

**Comment by bthemez** [comment]
Thank You for fixing it..:) Works Great!!
