### ISSUE TITLE
slight mis-match in video height width resulting in black bars

### ISSUE THREAD

**Issue by maxfancourt** [corbindavenport/superembed.js#5]
Just been trying this and really nice... it works really well... So hats off because it fixes a few issues which I came across with other scripts. The only thing I am seeing at the moment is a black bar to the left and right. I have quickly created an example and this effects mac Safari Firefox and chrome.. i haven't tested it on ie PC or any other PC browsers, just Macs.

The only way I got around it was by writing a style
iframe {height:102%}
and that does force it out to the correct size but this sounds like a bit of a mess to me. 
link to my example can be found here:
https://infinit.io/_/qauLDbM

if you coment out the  iframe {height:102%} style within index.css you will see that the video then has a black vertcal border on both sides

All the best 
Max

**Comment by corbindavenport** [comment]
I can see a noticeable improvement on your page, but when I tried applying it to the existing SuperEmbed demo [here](https://jsfiddle.net/0mncf0o8/), it actually caused black bars on the top and bottom. Maybe it's something to do with the CSS on your page?

**Comment by corbindavenport** [comment]
I just uploaded SuperEmbed.js 2.0, that should fix the scaling issues.

**Comment by maxfancourt** [comment]
Hi 
yep I can confirm the version SuperEmbed.js 2.0 has fixed the issue.. not sure what it was in my html/css or if it was a little conflict mismatch but the latest release works and scales correctly with the same HTML without the 102% and  no black bars visible anywhere.
Thanks max

**Comment by corbindavenport** [comment]
Great to hear it!
