### ISSUE TITLE
body, html height: 100%

### ISSUE THREAD

**Issue by Phil2017** [corbindavenport/superembed.js#8]
Hi there,

works great, but there seems to be a problem with the width / height calculation when i set the html and the body to a height of 100%... (Needed in my case since the project I'm working on is basically made of fullscreen sections). The iframe does not extend to the entire width of my screen (2560 x 1440px). 

`body, html { 
  height: 100%;
}`

**Comment by corbindavenport** [comment]
Try changing these lines in superembed.js:

```
if (height > maxHeight) {
  ratio = maxHeight / height; // Get ratio for scaling video
  iframe.setAttribute("height", maxHeight);
  iframe.setAttribute("width", width * ratio);
  width = width * ratio; // Reset width to match scaled video
  height = height * ratio; // Reset height to match scaled video
}
```

To this:

```
if (height > maxHeight) {
  ratio = maxHeight / height; // Get ratio for scaling video
  iframe.setAttribute("height", maxHeight);
  iframe.setAttribute("width", maxWidth);
  width = width * ratio; // Reset width to match scaled video
  height = height * ratio; // Reset height to match scaled video
}
```

And see if that fixes it.

**Comment by Phil2017** [comment]
It seemed so first, but this only centers the video and leaves it with space on the left / right side of the screen. (The iframe fills the whole screen, but the video inside if it does not scale enough to do the same... might be a problem of the video )... This happens only above 2357px... Everything fine below that number.

However in the meanwhile I've dumped the 100% height on the body so everything turns ok.
